### ISSUE TITLE
[EPIC] Rollups fraud proofs using QGB

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/blobstream-contracts#142]
As part of the efforts dedicated towards having an example of a Celestium, we will need to implement the following:

- [x] https://github.com/celestiaorg/quantum-gravity-bridge/issues/141
- [x] https://github.com/celestiaorg/protobuf3-solidity/issues/19
- [x] https://github.com/celestiaorg/quantum-gravity-bridge/issues/133
- [x] https://github.com/celestiaorg/quantum-gravity-bridge/issues/143
- [x] https://github.com/celestiaorg/celestia-core/issues/997

**Comment by adlerjohn** [comment]
Hmmm. What's the need for decoding the PFB transaction itself? The point of posting the data root was so that the blobs can be used without looking at transactions. An alternative would be to revert to using (potentially in addition to the data root) tuple roots and have each tuple include addition metadata.

**Comment by SweeXordious** [comment]
Thats to prove that a transaction, which has a specific commitment, was posted to Celestia.

We could use the blobs directly, but the proofs will be significantly bigger since we will need to send the whole rollup block to the solidity smart contract to be verified, as opposed to sending only the PFB.

Also, using the blobs or the subtree root doesn't allow us to check whether the blobs were posted to the provided `shareIndex`. Since, we can prove that some data was posted on some block, but we can't prove its position.

**Comment by adlerjohn** [comment]
I'm trying to find where the current scheme was first proposed but I'm drawing a blank. IIRC @musalbas suggested it.

Basically, in the current scheme rollup block producers post a new block to Ethereum and claim it uses a certain range or ranges of shares. The fun thing is _those shares don't actually have to be a complete blob, or even from a single blob_!

The fraud proof would then prove that a single tx in the rollup is 1) in the data root (only requires proving the tx, not the whole block), and 2) is in the range(s) claimed (trivial).

**Comment by SweeXordious** [comment]
@adlerjohn 
>  1) in the data root

We can prove that a transaction was posted in the block, but how would we prove that that transaction is the right transaction? We will need to parse it to verify if the commitment and share index is the same.

> 2) is in the range(s) claimed (trivial)

this means proving its position in the block? How would we do that?

**Comment by adlerjohn** [comment]
> how would we prove that that transaction is the right transaction

![image](https://user-images.githubusercontent.com/3290375/228935075-a1b52ae0-5462-4855-9ea5-a97309513bde.png)

You don't actually need to prove anything about transactions, or blobs. That's the neat part. The rollup block producer just claims "here's this range in the Celestia block, that's the rollup block." That range could be anything. Doesn't have to be a transaction or a blob.

> This means proving its position in the block? How would we do that?

Something along the lines of https://github.com/celestiaorg/nmt/pull/49

**Comment by musalbas** [comment]
I mean even if you wanted to prove the commitment of the blob (without using a range), can't you still do that by using a blob inclusion proof - not a pfb proof?
